pe

diff --git a/dot_bashrc b/dot_bashrc
--- a/dot_bashrc
+++ b/dot_bashrc
@@ -9,15 +9,27 @@ case $- in
     *i*) ;;
       *) return;;
 esac
-
+alias get_idf='. $HOME/esp/esp-idf/export.sh'
 alias vi="nvim"
 alias cd="z"
 alias weather="curl v2d.wttr.in/klaipeda"
+alias youtube-dl="yt-dlp --merge-output-format mp4"
+alias copy="cpst -c"
+alias paste="cpst -p"
+alias fzf=" fzf --style full --preview 'fzf-preview.sh {}' --bind 'focus:transform-header:file --brief {}'"
+
+fcd() {
+    local dir
+    dir=$(find * -type d | fzf --style full)  # Find directories and use fzf for selection
+    if [[ -n "$dir" ]]; then
+        builtin cd "$dir" || echo "Failed to change directory"
+    fi
+}
+
 
 if [ -z "$ZELLIJ" ]; then
     zellij attach usual|| zellij
 fi
-
 eval "$(zoxide init bash)"
 # don't put duplicate lines or lines starting with space in the history.
 # See bash(1) for more options
@@ -94,7 +106,7 @@ if [ -x /usr/bin/dircolors ]; then
     alias egrep='egrep --color=auto'
 fi
 
-    alias gpt='oatmeal'
+    alias gpt='aichat'
 # colored GCC warnings and errors
 #export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
 
@@ -132,3 +144,6 @@ eval "$(atuin init bash)"
 eval "$(starship init bash)"
 
 
+
+# Added by LM Studio CLI (lms)
+export PATH="$PATH:/home/mantas/.cache/lm-studio/bin"
